### ISSUE TITLE
Interactive Console isn't compatible with Ipython 5.x and later

### ISSUE THREAD

**Issue by sebdraven** [log2timeline/l2tpreg#9]
In Ipython 5.x The PromptManager class has been removed, and the prompt machinery simplified. See Custom Prompts to customise prompts with the new machinery.

So this code lines 1547 to 1550:
`    try:

      ipython_config.PromptManager.in_template = r''.join(prompt_strings)

    except AttributeError:

      ipython_config.prompt_manager.in_template = r''.join(prompt_strings)
`
raises an exception.

If I install ipython 4.0.0, the code is executed correctly.

**Comment by joachimmetz** [comment]
thx for the tip, I'll have to check what the earliest version Ipython is we need/want to be compatible with.

**Comment by joachimmetz** [comment]
I've made some changes in https://github.com/log2timeline/l2tpreg/commit/ee71fedb95b8013375cd8af7a804ba838e027b45. Reopen if this is still an issue.
